version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: imdb-analytics-hub
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_MAX_ALLOWED_PACKET: 1000000000000000
    ports:
      - "3306:3306"
    restart: unless-stopped
